spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/core?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 5996030ly
  redis:
    host: localhost
    port: 6379
    password: 5996030ly

customized:
  # 假设有个grayLog server
  gray-log:
    host: www.google.com
    port: 80