spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/core?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 5996030ly
  redis:
    host: localhost
    port: 6379
    password: 5996030ly
  elasticsearch:
    jest:
      uris: http://192.168.21.25:9200
      multi-threaded: true


customized:
  # 假设有个grayLog server
  gray-log:
    host: www.google.com
    port: 80
  elasticsearch:
    host: 192.168.21.25
    port: 9200